### ISSUE TITLE
On chrome mobile the generated deck is an .apkg.zip file, which has to be renamed before importing

### ISSUE THREAD

**Issue by RisingOrange** [infinyte7/ocloze#2]
When generating a deck on Chrome desktop, the resulting file is named Export-Deck.apkg. But when using the addon on mobile, I get Export-Deck.apkg.zip. To import it into Ankidroid I have to rename the file to Export-Deck.apkg.  This could confuse some users.

**Comment by krmanik** [comment]
I have tried some workaround but didn't work any. Also searched it on stackoverflow but didn't find valid solution. If you have idea then it will be fine.
Take a look
https://github.com/infinyte7/ocloze/blob/main/docs/js/deck-export.js#L126-#L141

**Comment by krmanik** [comment]
Now it will export deck in `.apkg` format
